coracle-social/coracle

src/agent/pool.ts
This will deduplicate incoming events before parsing them (yes, it skips `JSON.parse()`, which apparently is a slow beast) and verifying the signature.
I was told the performance effects of this are noticeable at naked eye.
=> optimize deduplication

src/partials/MediaSet.svelte
I always read this as "show +2", for example, when there are only two and since I am already seeing one it should be "show +1", but adding the word "all" will probably fix that and make it clear.
=> less confusing "show %d link previews".

src/app/views/MessagesList.svelte
Since the counter next to the tab count number of active conversations rather than unread messages, I think this makes more sense; being more intuitive.
=> altered tab name from "messages" to "conversations"

src/engine/media/commands.ts
This will fix the problem with upload to nostr.build not being authenticated as it should.
=> fix nip98 authorization and actually sign the header

src/engine/media/commands.ts
In some update Coracle stopped using only the url:
Tags.from(nip94_event).type("url").values().first()
To use all tags, that broke compatibility with all NIP96 servers except those that don't use delayed processing.
=> fix response from server

src/app/shared/EventDate.svelte, src/app/shared/EventInfo.svelte, src/util/misc.ts
Format time and date based on browser regional settings.
For example:
Before - dates were formatted in US style for everyone:
After - locale read from browser, for my country and language formatting will looks like:
Solution based on https://stackoverflow.com/a/57529410
=> Format time and date based on browser regional settings

Dockerfile
Adds a very basic Docker build. Looking for feedback to make it better! 
I am building multiarch images on my machine:
```
docker buildx build --platform linux/amd64,linux/arm64 -t coracle:latest . --push
```
Originally I ran `yarn run build` outside of Docker, which was faster, but less self contained. I added some changes recently which builds it completely in Docker.
Hopefully this PR is useful!
=> add a very basic docker image

src/app/views/UserProfile.svelte
In the case where a user has both their name and display_name set, they are unable to change the main identifier used for their profile.  Allowing them to set their display_name fixes this.
=> switch name to display_name in UserProfile

src/util/notes.ts
fixes #281 
I adjusted the regex to include relevant [Latin-1 Supplement](https://en.wikipedia.org/wiki/Latin-1_Supplement) characters
=> Accented Hashtags

src/engine/network/utils/connect.ts
Nip07 exceptions are suppressed - just printed into the logger using withExtension, but nip46 exceptions aren't caught, which means that DM handling of nip04 || nip44 is interrupted by nip04 exceptions and nip44 part is never called. This is the simplest way to overcome this..
=> Suppress nip46 exceptions

src/app/views/ChannelCreate.svelte, src/engine/state.ts, src/partials/Channel.svelte
resolves https://github.com/coracle-social/coracle/issues/378
single recipient where current user doesn't have inbox relays
no nip-17 toggle for group messages
disable ability to start a group message if not all group members have inbox relays
display confirm screen when in group chat and at least one person is missing inbox relays
=> Improve NIP-17 UX

src/app/MenuDesktopItem.svelte
Current view on desktop for shorter screens (I'm on a 13-inch macbook). The inspector said my browser window height was 595px with this:
Suggested view:
=> fix desktop menu item spacing on short screens (<650px height)

src/partials/Modal.svelte
Proposed fix for: https://github.com/coracle-social/coracle/issues/254
Is this the desired effect?
One problem is that not every scrollbar has 17px width (https://codepen.io/sambible/post/browser-scrollbar-widths)
=> Issue 254: Proposed fix

src/app/shared/FeedSummary.svelte, src/app/views/ChannelCreate.svelte, src/app/views/ChannelsListItem.svelte, src/app/views/RelayList.svelte, src/partials/Channel.svelte, src/partials/ImageInput.svelte, src/util/misc.ts, tests/unit/util/misc.spec.ts, tsconfig.json
This PR addresses #388. Pulled `displayList` into the project and made use of `Intl.ListFormt` instead of pure string concatenation. Maybe this is a slight improvement to the hurdak implementation? Added unit tests, so hopefully the original functionality is maintained. Also `tsconfig` was not happy, saying `Intl.ListFormat` did not exist, so I pointed the tsconfig target to `es2021` so we could have access to it. Not sure about the broader implications of this change.
=> 388 - Update the displayList implementation and move into the project

package-lock.json, package.json, src/app/views/Login.svelte
As per the pull request to `coracle-social/@welshman`, this pull request updates the package.json to use the nostr-signer-plugin from npmjs and updates `Login.svelte` to use the new API
=> Updated to nostr-signer-plugin 0.0.3 from npmjs

src/app/views/Bech32Entity.svelte, src/engine/requests.ts
Fallback to the pubkey write relays when naddr to not provide relay hints.
In deriveEvents, when loading the event, make sure we have some relay set in the request.
In NoteDetails and EventDetails, make sure we pass in some relays url so that we can load the event in the onMount callback
#448
=> Use pubkey relay if naddr does not provide relay hints

src/app/views/ChannelsDetail.svelte, src/engine/commands.ts, src/partials/Channel.svelte
Removing legacy message completely
- Show a warning on the top right of the screen if one pubkey is missing an inbox relay as in Flotilla
- Removed the NIP17 toggle as it is now the default.
- Still show a confirm modal if one pubkey is missing an inbox relay
=> Remove legacy message

src/app/editor/LinkExtension.ts
#473 
Have removed this bug that was a range error from tiptap.
Have tried many different commands to keep the range correct but nothing worked.
The solution I have is not the most elegant but it works everytime. Taking the real input being tracked by tiptap from (editor.state.doc.textContent) and check if there is a match against it, this avoid linkifying twice (which was the root issue)
Also the behaviour is slightly better now, on the previous version pressing enter and then space after creating a link would cancel the line break.
=> Fix link editor (for good)

src/app/shared/Note.svelte, src/app/shared/NoteActions.svelte, src/app/shared/NotePending.svelte, src/app/shared/NoteReply.svelte, src/app/views/NoteCreate.svelte, src/partials/Toast.svelte
NoteCreate:
- Close the modal once the event is signed
- Re-open the modal when/if the sent is cancelled
- Keep an entry in the draft store with id "note-create" to keep the note content during the modal lifecycle
NoteReply:
- Save the draft if the send is cancelled
- Align the note content text with the countdown text
- loading start at 20% to the left, the loading bar is now tweened animated rather than spring animated, for a smoother look
- The loading bar has a lighter background now as Daniele's screenshot
- When a Note is being replied, a reply with a background accent appear on the parent note, per Daniele's screenshot.
- The thing missing from Daniele's screenshot is the action popover next to the loading bar, the note actions (deleted, broadcast repost etc) can only be used once …
=> Refine delayed send

src/app.css, src/app/editor/SuggestionProfile.svelte, src/app/editor/Suggestions.svelte
Flotilla inspired suggestion dropdown
- Picture profile is now twice bigger
- User name display is bigger
- zero padding in the tippy-content container
- Display "no results" if no profiles are found
https://github.com/user-attachments/assets/082fa20c-0284-46e5-9abb-f11dbc1bc2b8
=> Enhance suggestions dropdown #486

src/app/views/ChannelsDetail.svelte, src/partials/Channel.svelte
What it looks like at the bottom of the chat history
There is another warning, once the user hit send, in a confirmation modal. You probably want to remove this one.
There was also an issue once you remove all your inbox relay, your npub still exist in the inboxPoliciesByPubkey store mapping, but the publicTags list is empty. I took this into consideration as well to check if you have any inbox relay.
=> inbox warning

src/app/editor/index.ts
It's a small config in nostr-editor extensions, just extend renderText to add `nostr:` in front of nevent, naddr, nprofile.
If we expect those entities to always be prefixed by `nostr:`it might be worth a PR on nostr-editor
=> Prefix all entities with nostr:

src/app/views/ChannelsDetail.svelte, src/engine/commands.ts, src/partials/Channel.svelte, src/partials/Message.svelte
There was an unnecessary roundtrip to the signer when sending a message. We were trying to unwrap a message we had just wrapped. This was fixed by publishing the rumor to the local repository before publishing the wrapped version to the relays.
The editor content is now cleared as soon as the message is sent. A loader replaces the send icon while the message is being wrapped and signed. Once the message is ready to be published, it appears in the channel, where it can still be canceled during the delay set by the user in the app settings.
https://github.com/user-attachments/assets/85ce862f-b65f-45d2-8dc0-6850593da574
=> Chat send is slow

src/partials/ThunkNotice.svelte
Very long url will go to the next line in the console, if the url is larger than the container it will result in an ellipsis
#517
=> accomodate long url in hud console

src/app/shared/FeedItem.svelte, src/app/views/UserContent.svelte, src/engine/state.ts
#498 
> Allow users to hide the "show x hidden replies" bit for muted notes
There is a new settings called "load_muted_replies", on by default, if turned off, it will hide the button
> Don't mute notes by the user's own pubkey
The only way to mute a note of your own is either to mute your own npub or that specific event id. If a word is muted and your note contain this word, it won't be hidden.
> Hide muted parents in feeds (sometimes a reply to a muted note will show up, just remove it and its parent if the parent is muted)
This one is the most challenging. It should be done in the new NoteReducer. 
The NoteReducer currently look for a parent at a depth of 2. If it turns out that the parent at the depth 3 is muted, we won't catch it.
The solution is obviously to loop until no parent is …
=> Improve mute

src/app/views/Help.svelte
When going through the login flow using a remote signer, I noticed that the "Browse Signer Apps" link on the `/help` page was linking to the nostrapps site but wasn't loading any signer options. However, the same link does work on the `/login` page. Changing the `/help` page nostrapps url to all lowercase (same as on the `login` page) fixes the issue. So just a one character change for a small inconvenience...
I tested locally with chromium and firefox and it now works as expected.
=> Change /help view nosrapps url to lowercase
